change date, &c. to gdate because osx uses BSD stuff by default (will need to change again to port back to the raspi but that's a problem for future ethan

diff --git a/grade b/grade
--- a/grade
+++ b/grade
@@ -12,7 +12,7 @@ validate () {
     CHUNKS=("${(f)REST}")
     for c in $CHUNKS
     do
-        if ! echo $c | grep -q -E '[a-z]{3}[0-9]{3,4},[0-9]{,3}'
+        if ! echo $c | ggrep -q -E '[a-z]{3}[0-9]{3,4},[0-9]{,3}'
         then
             echo "Poorly formatted.\n"
             return 0
@@ -30,7 +30,7 @@ sub_grade () {
 
     if [ "$1" != "false" ]
     then
-        EPOCH=$(date -d $2 +%s)
+        EPOCH=$(gdate -d $2 +%s)
         DIFF=$(((($EPOCH - $DUE_SEC) / 86400) + 1))
 
         BASE=$((100 - 25 * $DIFF))
@@ -48,7 +48,7 @@ ASSIGN=$(cat $2)
 BASE="https://canvas.northwestern.edu/api/v1"
 
 TEMP_DIR=temp_evaluate
-mkdir $TEMP_DIR
+mkdir -p $TEMP_DIR
 
 # calculate due date epoch
 
@@ -56,7 +56,8 @@ DUE_DATE=$(curl -s -X GET "$BASE/courses/$CID/assignments/$ASSIGN" \
     -H "$AUTH" \
     | jq -r '.due_at')
 
-DUE_SEC=$(date -d "$DUE_DATE" +%s)
+
+DUE_SEC=$(gdate -d "$DUE_DATE" +%s)
 
 # download subs
 
@@ -64,12 +65,13 @@ SUBS=$(curl -s -X GET "$BASE/courses/$CID/assignments/$ASSIGN/submissions" \
     -H "$AUTH" \
     -F "per_page=99")
 
+
 TRIMMED=$(echo $SUBS | \
     jq '[.[] | {
         uid: .user_id,
         timestamp: .submitted_at,
         late: .late,
-        url: .attachments[] .url
+        url: .attachments[]? .url
     }]')
 
 # upload grades i: original submission
@@ -94,9 +96,10 @@ do
     GRADE=$?
     echo "$USER submission grade: $GRADE"
 
-    curl -X PUT "$BASE/courses/$CID/assignments/$ASSIGN/submissions/$USER" \
-        -H "$AUTH" \
-        -F "submission[posted_grade]=$GRADE%"
+#    OUTPUT=$(curl -s -X PUT \
+#        "$BASE/courses/$CID/assignments/$ASSIGN/submissions/$USER" \
+#        -H "$AUTH" \
+#        -F "submission[posted_grade]=$GRADE%")
 done
 
 # TODO grade multiple submissions at once (one PUT request)
@@ -115,7 +118,7 @@ do
     do
         PARTS=("${(@s/,/)c}")
         NID=$PARTS[1]
-        SCORE=$(echo $PARTS[2] | sed 's///g')
+        SCORE=$(echo $PARTS[2] | sed 's///g')
 
         if ! (( ${+COUNTS[$NID]} ))
         then
@@ -164,24 +167,24 @@ RES=$(curl -s -X POST "$BASE/courses/$CID/assignments" \
     -F "assignment[description]=$DESC" \
     -F "assignment[submission_types]=$SUB_TYPE" \
     -F "assignment[points_possible]=$POINTS" \
-    -F "assignment[published]=false")
+    -F "assignment[published]=true")
 
 NEW_ASSIGN=$(echo "$RES" | jq '.id')
 
 # upload grades
-for key value in ${(kv)NETTOSIS}; do
-    if ! (( ${+COUNTS[$key]} ))
+for netid sisid in ${(kv)NETTOSIS}; do
+    if ! (( ${+COUNTS[$netid]} ))
     then
-        echo "missing $key"
+        echo "missing $netid"
     else
-        RESULT=$(( $TOTALS[$key] / $COUNTS[$key] ))
+        RESULT=$(( $TOTALS[$netid] / $COUNTS[$netid] ))
         if (( $RESULT > 100 )); then RESULT=100; fi
-        echo "$key $value $RESULT"
+        echo "$netid $sisid $RESULT"
 
-        FOO="$BASE/courses/$CID/assignments/$NEW_ASSIGN/submissions/$value/" 
-        curl -s -X PUT $FOO \
+        OUTPUT=$(curl -s -X PUT \
+            "$BASE/courses/$CID/assignments/$NEW_ASSIGN/submissions/$sisid" \
             -H "$AUTH" \
-            -F "submission[posted_grade]=$RESULT%"
+            -F "submission[posted_grade]=$RESULT%")
     fi
 done
 
